# This is a basic workflow to help you get started with Actions

name: Prisma IAC Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Checkov scan 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      env:
        PRISMA_API_URL: https://api4.prismacloud.io
      with:
        api-key: ${{ secrets.PCC_USER }}::${{ secrets.PCC_PASS }}
        #directory: "example/examplea"
        #check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
        #skip_check: CKV_AWS_1 # optional: skip a specific check_id. can be comma separated list
        soft_fail: true
        #framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
        output_format: cli
        quiet: false
        external_checks_dirs: ./checkov
        download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
        #log_level: DEBUG # optional: set log level. Default WARNING
    - name: Run yor action
      uses: bridgecrewio/yor-action@main
